version: "3.9"

services:
  registry:
    image: "registry:2"
    ports:
      - "5000:5000"
    restart: always
    volumes:
      - F:/Daten/Studium/Master/Masterarbeit/Entwicklung/Docker/Registry_UI:/var/lib/registry/
      - F:/Daten/Studium/Master/Masterarbeit/Entwicklung/Docker/Registry_UI/config.yml:/etc/docker/registry/config.yml

    networks:
      - registry-ui-net


  Joxit:
    image: "joxit/docker-registry-ui"
    ports:
      - "80:80"
    restart: always
    environment:
      - REGISTRY_URL=http://192.168.178.58:5000
      - REGISTRY_TITLE=My Local Docker Registry
      - DELETE_IMAGES=True
      - SHOW_CONTENT_DIGEST=True
    networks:
      - registry-ui-net
    depends_on:
      - registry


networks:
  registry-ui-net:
