#Compose Registry UI
version: "3.9"

services:
  registry:
    container_name: registry
    image: "registry:2"
    ports:
      - "5000:5000"
    restart: always
    volumes:
      - ~/Docker_Registry/compose/Master/compose:/var/lib/registry/
      - ~/Docker_Registry/compose/Master/compose/config.yml:/etc/docker/registry/config.yml
      - ~/Docker_Registry/compose/Master/compose/.htpasswd:/etc/docker/registry/.htpasswd
    environment:
      REGISTRY_STORAGE_DELETE_ENABLED: 'true'

  Joxit:
    container_name: registry_ui
    image: "joxit/docker-registry-ui"
    ports:
      - "8090:80"
    restart: always
    environment:
      NGINX_PROXY_PASS_URL: http://192.168.178.58:5000
      REGISTRY_TITLE: "Docker Registry"
      DELETE_IMAGES: "true"
      SHOW_CONTENT_DIGEST: "true"
    depends_on:
      - registry
